springdoc:
  swagger-ui:
    path: /api-doc

external-api:
  customs-clearance:
    uni-pass:
      base-url: https://unipass.customs.go.kr:38010
  delivery:
    cj-logistics:
      base-url: https://trace.cjlogistics.com
    kr-post:
      base-url: https://service.epost.go.kr
    winion-logis:
      base-url: https://winionlogis.com

logging:
  config: classpath:log/logback-prod.xml
